### ISSUE TITLE
Dependency list is incomplete

### ISSUE THREAD

**Issue by Shadlock0133** [jcyuan06/Kcalbeloh-System#10]
"Installation Checklist" includes folders for mods not mentioned in "Install Dependencies" section

**Comment by Shadlock0133** [comment]
if KopernicusExpansion is bundled with Kcalbeloh, is something preventing it from being added to CKAN?

**Comment by jcyuan06** [comment]
Yes. The newest version of KopernicusExpansion is not on CKAN so I have to bundle it.

**Comment by Shadlock0133** [comment]
then why not add it to CKAN as it currently is, with KopernicusExpansion bundled?

**Comment by jcyuan06** [comment]
CKAN doesn't allow bundling mods in this way. It only allows listing it as a dependency.
