### ISSUE TITLE
[v1.1.0] Planet System fails to load with RSS installed.

### ISSUE THREAD

**Issue by Mjrlun** [jcyuan06/Kcalbeloh-System#12]
Mod Versions:
Sigma Dimensions: v0.10.8
Real Solar System: v20.0.0.0
Scatterer: v0.0838
Environmental Visual Enhancements Redux: 1.11.71
(and many others)

Other Notes:
- The custom systems in general fail to load.
- Kerbol shows up, visible to the camera on the main screen
- Disabling "RunSharp.dll" in 'KopernicusExpansion/Plugins' did nothing
[Log](https://github.com/jcyuan06/Kcalbeloh-System/files/11953248/Log.zip)
[Full Ckan Modpack (Sigma Dimensions installed separately)](https://github.com/jcyuan06/Kcalbeloh-System/files/11953767/The.Modpack.zip)
![image](https://github.com/jcyuan06/Kcalbeloh-System/assets/84252662/7c118b7d-c38e-4e65-abb4-2baa15260b6d)

**Comment by jcyuan06** [comment]
Could you try to change line 143 in /KcalbelohSystem/OtherFeatures/Wormholes/WH-3141-A.cfg to `@Kopernicus:AFTER[RealSolarSystem]:HAS[@Body[Saturn]]`?

**Comment by jcyuan06** [comment]
Also I'm not sure whether parallax stock textures is compatible with RSS and Kcalbeloh at the same time. so I recommend to remove Parallax and Parallax Stock Textures to track the issue easier.

**Comment by Mjrlun** [comment]
I don't think RSS has updated to use Parallax (I haven't seen any ground features on Earth). Currently doing a fresh reinstall of the mods to ensure it wasn't a corrupt config hidden somewhere.

**Comment by Mjrlun** [comment]
The problem appears to be with the custom RSS Kopernicus config. I've fully reinstalled the entire modpack from scratch and the issue is the same.

**Comment by jcyuan06** [comment]
No. This file is necessary. Without it, this planet mod will be deleted by RSS. Have you tried the modification I mentioned before?

**Comment by Mjrlun** [comment]
That was in fact the error. I apologize for the holdup :)
Hope it can be fixed in the next patch

**Comment by jcyuan06** [comment]
Fixed in v1.1.1.
