### ISSUE TITLE
Singularity shaders glitch with planets near Kcalbeloh

### ISSUE THREAD

**Issue by hadron13** [jcyuan06/Kcalbeloh-System#15]
Well, I know this is a problem with Singularity, but the project seems dead, and I want to know if this can be a specific driver problem.

The problem is that, when you look away from Kcalbeloh, in a close planet such as Iomena (it's day side), the rendering glitchs out, showing orbit lines and sometimes a weird thing around the planet, such as in this screenshot:

 ![Iomena](https://github.com/jcyuan06/Kcalbeloh-System/assets/62845905/6bc9a815-ad79-400c-8e39-cc58fe0bb022)

Something to note is that I'm using Linux with an AMD GPU, Fedora 38 to be exact

And it also happens out of the map

**Comment by hadron13** [comment]
Other graphical mods:
Spectra & dependencies (EVE, Scatterer, etc)
Planetshine
TUFX

**Comment by hadron13** [comment]
Testing on an instance with only Kcalbeloh and required dependencies (no EVE/Scatterer) produces the same glitch.

**Comment by jcyuan06** [comment]
I haven't seen issues like this before. can you post your logs?

**Comment by hadron13** [comment]
Sure
here are the logs: 
[mylogs.zip](https://github.com/jcyuan06/Kcalbeloh-System/files/12270030/mylogs.zip)

**Comment by hadron13** [comment]
Yes, but last commit was in 2021, not likely to get any help from there. There is a similar open issue, not solved for over an year.
