### ISSUE TITLE
Noi and Simetra-Simeht barycenter have same SMA, causing sentinel telescope errors

### ISSUE THREAD

**Issue by StormCircuit** [jcyuan06/Kcalbeloh-System#16]
This is actually a bug in stock KSP but figured I would make you aware since it does affect Simetra-Simeht and Noi
Details on the cause are at the Snarkiverse issue tracker here, though it began as a KSPCF issue.
https://github.com/KSPSnark/Snarkiverse/issues/1

(original KSPCF issue is here: https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/158)

And I made an issue for it at the Kopernicus tracker as well:
https://github.com/Kopernicus/Kopernicus/issues/605

**Comment by jcyuan06** [comment]
Fixed in v1.1.5-beta
