### ISSUE TITLE
Wormholes config location?

### ISSUE THREAD

**Issue by pastadudes** [jcyuan06/Kcalbeloh-System#21]
Im trying to find the config for the wormholes so that i can edit it and fix it because in ksrss the wormhole on kerbol is missplaced, its placed between mars and venus and i want to edit it to somewhere around jupiter or mars

**Comment by pastadudes** [comment]
found it myself by accident lol

**Comment by jcyuan06** [comment]
It should be fixed in the newest release. Let me know if there is any issue.
