### ISSUE TITLE
Messed up graphics upon updating to v1.16

### ISSUE THREAD

**Issue by JackDaWac** [jcyuan06/Kcalbeloh-System#22]
Went to update to the new version of 1.16 and came upon this when checking out the system...:
![20240405120745_1](https://github.com/jcyuan06/Kcalbeloh-System/assets/166112093/f68091d6-5808-4a7b-a166-c54890d06288)
![20240405120754_1](https://github.com/jcyuan06/Kcalbeloh-System/assets/166112093/be3efcf9-bfff-46e0-8e51-01d88b66266c)
All the special icons were gone, textures were obviously messed up for the planets and Kchalbeloh itself, either having their textures gone completely or weird visual glitches happening on them. All of my visual mods for the Stock planets (Spectra, EVE Redux) were also not working when I booted the game up. Switching back to the last version though seemed to fix the problem. Updated through CKAN. Any idea what could be causing this? Help would be greatly appreciated! Thank you!

**Comment by jcyuan06** [comment]
can you upload your logs in [KSP folder]/Logs/Logs-Kopernicus.zip?

**Comment by JackDaWac** [comment]
Yes, sure thing
![Screenshot 2024-04-06 092507](https://github.com/jcyuan06/Kcalbeloh-System/assets/166112093/e449965e-e1e8-4bb7-8c8f-f8a501651790)
![Screenshot 2024-04-06 092650](https://github.com/jcyuan06/Kcalbeloh-System/assets/166112093/43fb00cc-86a6-48c3-9cfc-2049d03a7cb1)
![Screenshot 2024-04-06 092720](https://github.com/jcyuan06/Kcalbeloh-System/assets/166112093/c87b125f-fea9-43c0-9cbd-27ad5f676bc5)

**Comment by jcyuan06** [comment]
Ah I mean upload the file.

**Comment by jcyuan06** [comment]
Fixed in v1.1.7.
