### ISSUE TITLE
Several issues with Kerbol around Kcalbeloh

### ISSUE THREAD

**Issue by NoahFoloni** [jcyuan06/Kcalbeloh-System#27]
I have no idea what has happened, but when Kerbol is set around Kcalbeloh, several issues arise. Night takes up almost the entirety of each Kerbin day, and in the small part of the time when it's light out, the sky is broken, causing Scatterer and EVE clouds to appear black over kerbin. In the tracking station, launch sites can be seen orbiting/drifting around Kerbin. Upon first loading in, Kcalbeloh can be seen directly above kerbin's sky when I first start the game.
![Screenshot (336)](https://github.com/jcyuan06/Kcalbeloh-System/assets/171514904/3ce8c0ef-4dd9-43fc-866f-2a024580bbe2)
![Screenshot (337)](https://github.com/jcyuan06/Kcalbeloh-System/assets/171514904/de407ca9-28a3-4d97-8b9b-1eaf79d09011)
![Screenshot (338)](https://github.com/jcyuan06/Kcalbeloh-System/assets/171514904/7dcfd034-6ef0-46c3-b984-8222bfc2f4b0)
![Screenshot (339)](https://github.com/jcyuan06/Kcalbeloh-System/assets/171514904/49dc7216-2178-44b3-b819-8e77059aaa90)
![Screenshot (341)](https://github.com/jcyuan06/Kcalbeloh-System/assets/171514904/0b55afd0-074d-4f8e-97b5-9e0f0737a148)
I'm not sure what logs to attach, so if you could let me know I can get them sent over.

**Comment by NoahFoloni** [comment]
The mods I have installed are as follows:

Astronomer's Visual Pack (AstronomersVisualPack 3:v4.13)
Astronomer's Visual Pack-8k Textures (AVP-8kTextures v1.13)
BetterTimeWarpContinued (BetterTimeWarpCont 2.3.13)
Breaking Ground (BreakingGround-DLC 1.7.1)
ClickThrough Blocker (ClickThroughBlocker 1:2.1.10.21)
Community Resource Pack (CommunityResourcePack v112.0.1)
Community Terrain Texture Pack (CommunityTerrainTexturePack 1:1.0.5)
Custom Barn Kit (CustomBarnKit 1.1.22.0)
Environmental Visual Enhancements Redux (EnvironmentalVisualEnhancements 3:1.11.7.1)
Harmony 2 (Harmony2 2.2.1.0)
HyperEdit (HyperEdit 1.5.8.0)
Kcalbeloh System (KcalbelohSystem v1.1.7)
Kcalbeloh System 8k Textures (KcalbelohSystem-Textures-8k v1.1.7)
Kerbal Engineer Redux (KerbalEngineerRedux 1.1.9.0)
Kopernicus Expansion Continued-er (KopernicusExpansionContinueder Beta9.1.1)
Kopernicus Expansion Continued-er Stock Configs (KopernicusExpansionContinueder-StockConfigs Beta9.1.1)
Kopernicus Planetary System Modifier (Kopernicus 2:release-1.12.1-204)
KSP Community Fixes (KSPCommunityFixes 1.35.2)
Making History (MakingHistory-DLC 1.12.1)
ManeuverNodeSplitter (NodeSplitter 1.8.0.3)
MechJeb 2 (MechJeb2 2.14.3.0)
MechJeb and Engineer for all! (MechJebForAll 1.3.0.7)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.10.0)
Module Manager (ModuleManager 4.2.3)
Outer Planets Mod (OuterPlanetsMod 2:2.2.10)
Outer Planets Mod - Parallax with Scatters (Parallax-OuterPlanetsMod v1.0.5)
Parallax (Parallax 2.0.6)
Parallax - Stock Planet Textures (Parallax-StockTextures 2.0.0)
Parallax - Stock Scatter Textures (Parallax-StockScatterTextures 2.0.1)
ReStock (ReStock 1.4.5)
ReStock+ (ReStockPlus 1.4.5)
Scatterer (Scatterer 3:v0.0838)
Scatterer Default Config (Scatterer-config 3:v0.0838)
Scatterer Sunflare (Scatterer-sunflare 3:v0.0838)
Singularity (Singularity 0.991)
SpaceTux Library (SpaceTuxLibrary 0.0.8.6)
Station Keeping (StationKeeping 1:0.2.3.1)
Toolbar Controller (ToolbarController 1:0.1.9.11)
Tracking Station Evolved (TrackingStationEvolved 7.0)
Vertex Mitchell-Netravali Filtered Heightmap (VertexMitchellNetravaliHeightMap 0.3)
Waterfall - Restock (WaterfallRestock 0.2.3)
Waterfall Core (Waterfall 0.9.0)

**Comment by 303404Hi** [comment]
(First apologize for my poor English)
------------------------------------------------------------------------------------------------------------------------------------------------
## Problems
Bro I have met almost the same problem yet, but finally solved it.
The screenshots before solving it:
_black clouds when start
![Image](https://github.com/user-attachments/assets/513ab7a4-0c78-4556-93fd-9e46f5965223)
_Kcalbeloh on sky in KSC
![Image](https://github.com/user-attachments/assets/0277e8e7-38b7-45db-ae6e-b0ed4637de8b)
_launch pads outside Kerbin
![Image](https://github.com/user-attachments/assets/0835bf9a-d821-4c9e-aee3-b1143f0adbfb)
------------------------------------------------------------------------------------------------------------------------------------------------
## My Trying and Solving
I removed all my mods(all in GameData except Squad,SquadExpansion,ModuleManager.4.2.3.dll) and rebuilded the game in another folder. Then added the mods one by one(I didn't add some of them, and imported some new ones), found it useless.

Then I checked my KSP.log and found nothing, so I searched for the configs to let Kerbol orbit Kcalbeloh, and found this: KerbolAroundKcalbeloh.cfg in /GameData/KcalbelohSystem/OtherFeatures

I tried to check the logics in the file. After learning basic ModuleManager Patches on https://github.com/sarbian/ModuleManager/wiki/Module-Manager-Syntax,
I changed some "@" (which means edit) into "%" (witch means edit or create),
**AND EVERYTHING WAS FIXED!!!**

Solved screenshots here:
_solved start views_
 ![Image](https://github.com/user-attachments/assets/becb9c7d-a87a-4585-8d16-a82e594d649a)
_solved KSC (with Raymatched Volumetric Clouds)
 ![Image](https://github.com/user-attachments/assets/ee681653-f6d7-4e5b-9446-4856c0560a1a)
_solved launch pads
 ![Image](https://github.com/user-attachments/assets/ab4d69ff-bcab-45ab-9bd4-85d903d47bd7)
------------------------------------------------------------------------------------------------------------------------------------------------
## Solving Methods
So shortly, problem solving steps:
1.Take out all mods (proved to be nesessary), or delete the whole game folder is better
2.Add Kcalbeloh mods (see https://github.com/jcyuan06/Kcalbeloh-System?tab=readme-ov-file#installation-checklist)
3.**IMPORTANT**: Replace **KerbolAroundKcalbeloh.cfg** in **/GameData/KcalbelohSystem/OtherFeatures** with **the file below**
4.Set DistanceFactor in **Kcalbeloh System Settings.cfg** in **/GameData/KcalbelohSystem/** to **0**
5.Start the game, check if everything is fine
6.Add mods back (I suggest reinstall them with CKAN), start the game and check again before adding EVE&Scatterer configs
7.Add EVE&Scatterer configs, do the final check
8.Open your worlds carefully, set Kerbol around Kcalbeloh may cause some problems
9.Enjoy your time!

Fixed KerbolAroundKcalbeloh.cfg: (I will try to put it on github files if jcyuan06 allows)
[KerbolAroundKcalbeloh.zip](https://github.com/user-attachments/files/20489434/KerbolAroundKcalbeloh.zip)
