### ISSUE TITLE
Kcalbelohs accretion disk's texture is missing

### ISSUE THREAD

**Issue by themanofpolybridge2** [jcyuan06/Kcalbeloh-System#7]
When i look at Kcalbeloh, all i see is a black sphere with a glitchy accretion disk that has the unknown texture (the question mark in red on a white background) and on singularitys config page/ui i saw the accretion disk path was "KcalbelohSystem\PluginData\disk.dds"
If anyone had this bug and fixed it, please let me know how to fix it.

**Comment by jcyuan06** [comment]
You are using the older version of Singularity. The newest version is 0.991 and can be found on Spacedock, GitHub(pre-release) or CKAN.

**Comment by themanofpolybridge2** [comment]
oh ok
