### ISSUE TITLE
KSP freezes when landing on a moon or planet

### ISSUE THREAD

**Issue by KolonelKerbal** [jcyuan06/Kcalbeloh-System#9]
It works fine in orbit, the atmosphere, you name it. But right when I try to land on the body, the game turns into a white shade before prompting "Not responding". any ideas as to why?

If you want to know my specs:
Intel i7 11500 11th gen
RTX 3080 Laptop GPU
16 gigs of ram

**Comment by jcyuan06** [comment]
Can you upload your logs?

**Comment by KolonelKerbal** [comment]
I'll try

**Comment by KolonelKerbal** [comment]
[KSP.log](https://github.com/jcyuan06/Kcalbeloh-System/files/10932322/KSP.log)

does this work?

**Comment by jcyuan06** [comment]
Which parallax version are you installing? Kcalbeloh only works with the newest version.

**Comment by KolonelKerbal** [comment]
oh...Scheiße
